public class mapp {
   public void mappp() 
   {
      Map <string,string> m1 = new map <string,string> (); 
      m1.put('Zara', '8');
      m1.put('Mahnaz','31');
      m1.put('Ayan', '12');
      m1.put('Daisy', '14');
      system.debug('\t' + m1);
       system.debug(+m1.get('Zara'));
       system.debug(+m1.containsKey('vikas'));
       system.debug(+m1.keySet());
       system.debug(+m1.values());
       
   }
}